services:
  db:
    container_name: "recipe_db"
    image: postgres:16-alpine
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_DB=postgres${DB}
    ports:
      - "5444:5432"
    networks:
      - "custom"

  db_test:
    container_name: "recipe_db_test"
    image: postgres:16-alpine
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_USER=${TUSER}
      - POSTGRES_PASSWORD=${TPASS}
      - POSTGRES_DB=${TDB}
    ports:
      - "5433:5432"
    networks:
      - "custom"

networks:
  custom:
    driver: bridge
