services:
  db_test:
    container_name: "db_test"
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TUSER}
      - POSTGRES_PASSWORD=${TPASS}
      - POSTGRES_DB=${TDB}
    ports:
      - "5432:5432"