server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # 1) Logs FastAPI
  - job_name: fastapi
    static_configs:
      - targets:
        - localhost
        labels:
          job: fastapi
          __path__: /app/logs/*log

  # 2) System logs
  - job_name: system
    static_configs:
      - targets:
        - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  # 3) Docker-logs
  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - targets:
        - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
